//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StrategoApp.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StrategoApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Abysswatcher.
        /// </summary>
        public static string Abysswatcher_Label {
            get {
                return ResourceManager.GetString("Abysswatcher_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Accept.
        /// </summary>
        public static string Accept_Button {
            get {
                return ResourceManager.GetString("Accept_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Account already exist.
        /// </summary>
        public static string AccountAlreadyExist_Title {
            get {
                return ResourceManager.GetString("AccountAlreadyExist_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This account already exist, try with another one.
        /// </summary>
        public static string AccountAlreadyExistMessage_Label {
            get {
                return ResourceManager.GetString("AccountAlreadyExistMessage_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add.
        /// </summary>
        public static string AddFriend_Button {
            get {
                return ResourceManager.GetString("AddFriend_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apprentice.
        /// </summary>
        public static string Apprentice_Button {
            get {
                return ResourceManager.GetString("Apprentice_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apprentice.
        /// </summary>
        public static string Apprentice_Label {
            get {
                return ResourceManager.GetString("Apprentice_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Archfiend.
        /// </summary>
        public static string Archfiend_Label {
            get {
                return ResourceManager.GetString("Archfiend_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your account has been banned.
        /// </summary>
        public static string BannedAccount_Label {
            get {
                return ResourceManager.GetString("BannedAccount_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancel.
        /// </summary>
        public static string Cancel_Button {
            get {
                return ResourceManager.GetString("Cancel_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Casual player.
        /// </summary>
        public static string Casual_Button {
            get {
                return ResourceManager.GetString("Casual_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your password has been changed succesfully.
        /// </summary>
        public static string ChangedPasswordMessage_Label {
            get {
                return ResourceManager.GetString("ChangedPasswordMessage_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Change Password.
        /// </summary>
        public static string ChangePassword_Button {
            get {
                return ResourceManager.GetString("ChangePassword_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Change Password.
        /// </summary>
        public static string ChangePassword_Title {
            get {
                return ResourceManager.GetString("ChangePassword_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Chat.
        /// </summary>
        public static string Chat_Label {
            get {
                return ResourceManager.GetString("Chat_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Check profile.
        /// </summary>
        public static string CheckProfile_Button {
            get {
                return ResourceManager.GetString("CheckProfile_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Code.
        /// </summary>
        public static string Code_Label {
            get {
                return ResourceManager.GetString("Code_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Competitive.
        /// </summary>
        public static string Competitive_Button {
            get {
                return ResourceManager.GetString("Competitive_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Competitive.
        /// </summary>
        public static string Competitive_Label {
            get {
                return ResourceManager.GetString("Competitive_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create lobby.
        /// </summary>
        public static string CreateLobby_Button {
            get {
                return ResourceManager.GetString("CreateLobby_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Current Password.
        /// </summary>
        public static string CurrentPassword_Label {
            get {
                return ResourceManager.GetString("CurrentPassword_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DarkKnight.
        /// </summary>
        public static string DarkKnight_Label {
            get {
                return ResourceManager.GetString("DarkKnight_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Darkwraith.
        /// </summary>
        public static string Darkwraith_Label {
            get {
                return ResourceManager.GetString("Darkwraith_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Connection error.
        /// </summary>
        public static string DatabaseConnectionError_Title {
            get {
                return ResourceManager.GetString("DatabaseConnectionError_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Connection error has ocurred, try again later.
        /// </summary>
        public static string DatabaseConnectionErrorMessage_Label {
            get {
                return ResourceManager.GetString("DatabaseConnectionErrorMessage_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Defeat.
        /// </summary>
        public static string Defeat_Label {
            get {
                return ResourceManager.GetString("Defeat_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter your email.
        /// </summary>
        public static string EnterEmail_Label {
            get {
                return ResourceManager.GetString("EnterEmail_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Some fields are in blank.
        /// </summary>
        public static string FieldsInBlank_Label {
            get {
                return ResourceManager.GetString("FieldsInBlank_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Forgot your password?.
        /// </summary>
        public static string ForgotPassword_Label {
            get {
                return ResourceManager.GetString("ForgotPassword_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sent request to.
        /// </summary>
        public static string FriendRequestMessage_Label {
            get {
                return ResourceManager.GetString("FriendRequestMessage_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Friend requests.
        /// </summary>
        public static string FriendRequests_Title {
            get {
                return ResourceManager.GetString("FriendRequests_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Friends.
        /// </summary>
        public static string Friends_Button {
            get {
                return ResourceManager.GetString("Friends_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Friends.
        /// </summary>
        public static string Friends_Title {
            get {
                return ResourceManager.GetString("Friends_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lobby is full.
        /// </summary>
        public static string FullLobby_Label {
            get {
                return ResourceManager.GetString("FullLobby_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Games lost.
        /// </summary>
        public static string GamesLost_Label {
            get {
                return ResourceManager.GetString("GamesLost_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Games played.
        /// </summary>
        public static string GamesPlayed_Label {
            get {
                return ResourceManager.GetString("GamesPlayed_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Games won.
        /// </summary>
        public static string GamesWon_Label {
            get {
                return ResourceManager.GetString("GamesWon_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GrimReaper.
        /// </summary>
        public static string GrimReaper_Label {
            get {
                return ResourceManager.GetString("GrimReaper_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hellhound.
        /// </summary>
        public static string Hellhound_Label {
            get {
                return ResourceManager.GetString("Hellhound_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter a valid code.
        /// </summary>
        public static string InvalidCode_Label {
            get {
                return ResourceManager.GetString("InvalidCode_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid mail (ex: name@domain.com).
        /// </summary>
        public static string InvalidMail_Label {
            get {
                return ResourceManager.GetString("InvalidMail_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid password (8-32 characters, 1 number).
        /// </summary>
        public static string InvalidPassword_Label {
            get {
                return ResourceManager.GetString("InvalidPassword_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid name (4-16 characters).
        /// </summary>
        public static string InvalidUsername_Label {
            get {
                return ResourceManager.GetString("InvalidUsername_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invite.
        /// </summary>
        public static string InviteToLobby_Button {
            get {
                return ResourceManager.GetString("InviteToLobby_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Join.
        /// </summary>
        public static string Join_Button {
            get {
                return ResourceManager.GetString("Join_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Join to lobby.
        /// </summary>
        public static string LobbyCode_Title {
            get {
                return ResourceManager.GetString("LobbyCode_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Login.
        /// </summary>
        public static string Login_Button {
            get {
                return ResourceManager.GetString("Login_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a LogIn.
        /// </summary>
        public static string Login_Title {
            get {
                return ResourceManager.GetString("Login_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Login as invited.
        /// </summary>
        public static string LoginAsInvited_Button {
            get {
                return ResourceManager.GetString("LoginAsInvited_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Logout.
        /// </summary>
        public static string Logout_Button {
            get {
                return ResourceManager.GetString("Logout_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The player has been reported, thanks for your contribution.
        /// </summary>
        public static string MessageReport_Label {
            get {
                return ResourceManager.GetString("MessageReport_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Misbehavior.
        /// </summary>
        public static string Misbehavior_Button {
            get {
                return ResourceManager.GetString("Misbehavior_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Misbehavior.
        /// </summary>
        public static string Misbehavior_Label {
            get {
                return ResourceManager.GetString("Misbehavior_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Name change.
        /// </summary>
        public static string NameChange_Label {
            get {
                return ResourceManager.GetString("NameChange_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Necrofiend.
        /// </summary>
        public static string Necrofiend_Label {
            get {
                return ResourceManager.GetString("Necrofiend_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Necronomicon.
        /// </summary>
        public static string Necronomicon_Label {
            get {
                return ResourceManager.GetString("Necronomicon_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New Password.
        /// </summary>
        public static string NewPassword_Label {
            get {
                return ResourceManager.GetString("NewPassword_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nightmare.
        /// </summary>
        public static string Nightmare_Label {
            get {
                return ResourceManager.GetString("Nightmare_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This account doesn´t exist.
        /// </summary>
        public static string NonexistentAccount_Label {
            get {
                return ResourceManager.GetString("NonexistentAccount_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Code doesn&apos;t exist.
        /// </summary>
        public static string NonexistentCode_Label {
            get {
                return ResourceManager.GetString("NonexistentCode_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Novice player.
        /// </summary>
        public static string NovicePlayer_Button {
            get {
                return ResourceManager.GetString("NovicePlayer_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Novice player.
        /// </summary>
        public static string NovicePlayer_Label {
            get {
                return ResourceManager.GetString("NovicePlayer_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Offensive language.
        /// </summary>
        public static string OffensiveLanguage_Button {
            get {
                return ResourceManager.GetString("OffensiveLanguage_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Offline.
        /// </summary>
        public static string Offline_Label {
            get {
                return ResourceManager.GetString("Offline_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Online.
        /// </summary>
        public static string Online_Label {
            get {
                return ResourceManager.GetString("Online_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password Changed.
        /// </summary>
        public static string PasswordChanged_Title {
            get {
                return ResourceManager.GetString("PasswordChanged_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Place your pieces on the board.
        /// </summary>
        public static string PlacePiecesOnBoard_Label {
            get {
                return ResourceManager.GetString("PlacePiecesOnBoard_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Play.
        /// </summary>
        public static string Play_Button {
            get {
                return ResourceManager.GetString("Play_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Insert player id.
        /// </summary>
        public static string PlayerIdPrompt_Label {
            get {
                return ResourceManager.GetString("PlayerIdPrompt_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Potiontrap.
        /// </summary>
        public static string Potiontrap_Label {
            get {
                return ResourceManager.GetString("Potiontrap_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Profile.
        /// </summary>
        public static string Profile_Title {
            get {
                return ResourceManager.GetString("Profile_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pro player.
        /// </summary>
        public static string ProPlayer_Button {
            get {
                return ResourceManager.GetString("ProPlayer_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pro player.
        /// </summary>
        public static string ProPlayer_Label {
            get {
                return ResourceManager.GetString("ProPlayer_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Register.
        /// </summary>
        public static string Register_Title {
            get {
                return ResourceManager.GetString("Register_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Remove.
        /// </summary>
        public static string Remove_Button {
            get {
                return ResourceManager.GetString("Remove_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure you want to remove this friend?.
        /// </summary>
        public static string RemoveFriendConfirmationMessage_Label {
            get {
                return ResourceManager.GetString("RemoveFriendConfirmationMessage_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Report.
        /// </summary>
        public static string Report_Button {
            get {
                return ResourceManager.GetString("Report_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Report.
        /// </summary>
        public static string Report_Title {
            get {
                return ResourceManager.GetString("Report_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rules violation.
        /// </summary>
        public static string RulesViolation_Button {
            get {
                return ResourceManager.GetString("RulesViolation_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save.
        /// </summary>
        public static string Save_Button {
            get {
                return ResourceManager.GetString("Save_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Scoreboard.
        /// </summary>
        public static string Scoreboard_Button {
            get {
                return ResourceManager.GetString("Scoreboard_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Scoreboard.
        /// </summary>
        public static string Scoreboard_Title {
            get {
                return ResourceManager.GetString("Scoreboard_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Search player.
        /// </summary>
        public static string SearchPlayer_Label {
            get {
                return ResourceManager.GetString("SearchPlayer_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Search player.
        /// </summary>
        public static string SearchPlayer_Title {
            get {
                return ResourceManager.GetString("SearchPlayer_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select Profile Picture.
        /// </summary>
        public static string SelectProfilePicture_Title {
            get {
                return ResourceManager.GetString("SelectProfilePicture_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Send.
        /// </summary>
        public static string Send_Button {
            get {
                return ResourceManager.GetString("Send_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Server connection lost.
        /// </summary>
        public static string ServerConnectionLost_Title {
            get {
                return ResourceManager.GetString("ServerConnectionLost_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Server connection lost, try again later.
        /// </summary>
        public static string ServerConnectionLostMessage_Label {
            get {
                return ResourceManager.GetString("ServerConnectionLostMessage_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sign up.
        /// </summary>
        public static string SignUp_Button {
            get {
                return ResourceManager.GetString("SignUp_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your account has been created.
        /// </summary>
        public static string SignUpMessage_Label {
            get {
                return ResourceManager.GetString("SignUpMessage_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Soulhunter.
        /// </summary>
        public static string Soulhunter_Label {
            get {
                return ResourceManager.GetString("Soulhunter_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Stratego.
        /// </summary>
        public static string Stratego_Label {
            get {
                return ResourceManager.GetString("Stratego_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Toxicity.
        /// </summary>
        public static string Toxicity_Button {
            get {
                return ResourceManager.GetString("Toxicity_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Trapbreaker.
        /// </summary>
        public static string Trapbreaker_Label {
            get {
                return ResourceManager.GetString("Trapbreaker_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Use of hacks.
        /// </summary>
        public static string UseHacks_Button {
            get {
                return ResourceManager.GetString("UseHacks_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email.
        /// </summary>
        public static string UserMail_Label {
            get {
                return ResourceManager.GetString("UserMail_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Username.
        /// </summary>
        public static string UserName_Label {
            get {
                return ResourceManager.GetString("UserName_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password.
        /// </summary>
        public static string UserPassword_Label {
            get {
                return ResourceManager.GetString("UserPassword_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Victories.
        /// </summary>
        public static string Victories_Label {
            get {
                return ResourceManager.GetString("Victories_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Victory.
        /// </summary>
        public static string Victory_Label {
            get {
                return ResourceManager.GetString("Victory_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Wrong Password.
        /// </summary>
        public static string WrongPassword_Label {
            get {
                return ResourceManager.GetString("WrongPassword_Label", resourceCulture);
            }
        }
    }
}
