//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StrategoDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Games
    {
        public int WonGames { get; set; }
        public int DeafeatGames { get; set; }
        public int AccountId { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
