//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StrategoApp.ProfileService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PlayerInfoResponse", Namespace="http://schemas.datacontract.org/2004/07/StrategoServices.Data.DTO")]
    [System.SerializableAttribute()]
    public partial class PlayerInfoResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private StrategoApp.ProfileService.PlayerInfoShownDTO ProfileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private StrategoApp.ProfileService.OperationResult ResultField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public StrategoApp.ProfileService.PlayerInfoShownDTO Profile {
            get {
                return this.ProfileField;
            }
            set {
                if ((object.ReferenceEquals(this.ProfileField, value) != true)) {
                    this.ProfileField = value;
                    this.RaisePropertyChanged("Profile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public StrategoApp.ProfileService.OperationResult Result {
            get {
                return this.ResultField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultField, value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PlayerInfoShownDTO", Namespace="http://schemas.datacontract.org/2004/07/StrategoServices.Data.DTO")]
    [System.SerializableAttribute()]
    public partial class PlayerInfoShownDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LabelPathField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PicturePathField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LabelPath {
            get {
                return this.LabelPathField;
            }
            set {
                if ((object.ReferenceEquals(this.LabelPathField, value) != true)) {
                    this.LabelPathField = value;
                    this.RaisePropertyChanged("LabelPath");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PicturePath {
            get {
                return this.PicturePathField;
            }
            set {
                if ((object.ReferenceEquals(this.PicturePathField, value) != true)) {
                    this.PicturePathField = value;
                    this.RaisePropertyChanged("PicturePath");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OperationResult", Namespace="http://schemas.datacontract.org/2004/07/StrategoServices.Data")]
    [System.SerializableAttribute()]
    public partial class OperationResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsDataBaseErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsSuccessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsDataBaseError {
            get {
                return this.IsDataBaseErrorField;
            }
            set {
                if ((this.IsDataBaseErrorField.Equals(value) != true)) {
                    this.IsDataBaseErrorField = value;
                    this.RaisePropertyChanged("IsDataBaseError");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSuccess {
            get {
                return this.IsSuccessField;
            }
            set {
                if ((this.IsSuccessField.Equals(value) != true)) {
                    this.IsSuccessField = value;
                    this.RaisePropertyChanged("IsSuccess");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PlayerStatisticsResponse", Namespace="http://schemas.datacontract.org/2004/07/StrategoServices.Data.DTO")]
    [System.SerializableAttribute()]
    public partial class PlayerStatisticsResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private StrategoApp.ProfileService.OperationResult ResultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private StrategoApp.ProfileService.PlayerStatisticsDTO StatisticsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public StrategoApp.ProfileService.OperationResult Result {
            get {
                return this.ResultField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultField, value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public StrategoApp.ProfileService.PlayerStatisticsDTO Statistics {
            get {
                return this.StatisticsField;
            }
            set {
                if ((object.ReferenceEquals(this.StatisticsField, value) != true)) {
                    this.StatisticsField = value;
                    this.RaisePropertyChanged("Statistics");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PlayerStatisticsDTO", Namespace="http://schemas.datacontract.org/2004/07/StrategoServices.Data.DTO")]
    [System.SerializableAttribute()]
    public partial class PlayerStatisticsDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LostGamesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalGamesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int WonGamesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LostGames {
            get {
                return this.LostGamesField;
            }
            set {
                if ((this.LostGamesField.Equals(value) != true)) {
                    this.LostGamesField = value;
                    this.RaisePropertyChanged("LostGames");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalGames {
            get {
                return this.TotalGamesField;
            }
            set {
                if ((this.TotalGamesField.Equals(value) != true)) {
                    this.TotalGamesField = value;
                    this.RaisePropertyChanged("TotalGames");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int WonGames {
            get {
                return this.WonGamesField;
            }
            set {
                if ((this.WonGamesField.Equals(value) != true)) {
                    this.WonGamesField = value;
                    this.RaisePropertyChanged("WonGames");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PlayerFriendsResponse", Namespace="http://schemas.datacontract.org/2004/07/StrategoServices.Data.DTO")]
    [System.SerializableAttribute()]
    public partial class PlayerFriendsResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int[] FriendsIdsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private StrategoApp.ProfileService.OperationResult ResultField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int[] FriendsIds {
            get {
                return this.FriendsIdsField;
            }
            set {
                if ((object.ReferenceEquals(this.FriendsIdsField, value) != true)) {
                    this.FriendsIdsField = value;
                    this.RaisePropertyChanged("FriendsIds");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public StrategoApp.ProfileService.OperationResult Result {
            get {
                return this.ResultField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultField, value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OtherPlayerInfoResponse", Namespace="http://schemas.datacontract.org/2004/07/StrategoServices.Data.DTO")]
    [System.SerializableAttribute()]
    public partial class OtherPlayerInfoResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private StrategoApp.ProfileService.OtherPlayerInfoDTO PlayerInfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private StrategoApp.ProfileService.OperationResult ResultField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public StrategoApp.ProfileService.OtherPlayerInfoDTO PlayerInfo {
            get {
                return this.PlayerInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.PlayerInfoField, value) != true)) {
                    this.PlayerInfoField = value;
                    this.RaisePropertyChanged("PlayerInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public StrategoApp.ProfileService.OperationResult Result {
            get {
                return this.ResultField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultField, value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OtherPlayerInfoDTO", Namespace="http://schemas.datacontract.org/2004/07/StrategoServices.Data.DTO")]
    [System.SerializableAttribute()]
    public partial class OtherPlayerInfoDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsFriendField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private StrategoApp.ProfileService.PlayerInfoShownDTO PlayerInfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private StrategoApp.ProfileService.PlayerStatisticsDTO PlayerStatisticsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsFriend {
            get {
                return this.IsFriendField;
            }
            set {
                if ((this.IsFriendField.Equals(value) != true)) {
                    this.IsFriendField = value;
                    this.RaisePropertyChanged("IsFriend");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public StrategoApp.ProfileService.PlayerInfoShownDTO PlayerInfo {
            get {
                return this.PlayerInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.PlayerInfoField, value) != true)) {
                    this.PlayerInfoField = value;
                    this.RaisePropertyChanged("PlayerInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public StrategoApp.ProfileService.PlayerStatisticsDTO PlayerStatistics {
            get {
                return this.PlayerStatisticsField;
            }
            set {
                if ((object.ReferenceEquals(this.PlayerStatisticsField, value) != true)) {
                    this.PlayerStatisticsField = value;
                    this.RaisePropertyChanged("PlayerStatistics");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TopPlayersResponse", Namespace="http://schemas.datacontract.org/2004/07/StrategoServices.Data.DTO")]
    [System.SerializableAttribute()]
    public partial class TopPlayersResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private StrategoApp.ProfileService.OperationResult ResultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int[] TopPlayersIdsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public StrategoApp.ProfileService.OperationResult Result {
            get {
                return this.ResultField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultField, value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int[] TopPlayersIds {
            get {
                return this.TopPlayersIdsField;
            }
            set {
                if ((object.ReferenceEquals(this.TopPlayersIdsField, value) != true)) {
                    this.TopPlayersIdsField = value;
                    this.RaisePropertyChanged("TopPlayersIds");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProfileService.IProfileDataService", CallbackContract=typeof(StrategoApp.ProfileService.IProfileDataServiceCallback))]
    public interface IProfileDataService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfileDataService/GetPlayerStatistics", ReplyAction="http://tempuri.org/IProfileDataService/GetPlayerStatisticsResponse")]
        void GetPlayerStatistics(int playerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfileDataService/GetPlayerStatistics", ReplyAction="http://tempuri.org/IProfileDataService/GetPlayerStatisticsResponse")]
        System.Threading.Tasks.Task GetPlayerStatisticsAsync(int playerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfileDataService/LogOut", ReplyAction="http://tempuri.org/IProfileDataService/LogOutResponse")]
        void LogOut(int playerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfileDataService/LogOut", ReplyAction="http://tempuri.org/IProfileDataService/LogOutResponse")]
        System.Threading.Tasks.Task LogOutAsync(int playerId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProfileDataServiceCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IProfileDataService/PlayerInfo")]
        void PlayerInfo([System.ServiceModel.MessageParameterAttribute(Name="playerInfo")] StrategoApp.ProfileService.PlayerInfoResponse playerInfo1);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IProfileDataService/PlayerStatistics")]
        void PlayerStatistics([System.ServiceModel.MessageParameterAttribute(Name="playerStatistics")] StrategoApp.ProfileService.PlayerStatisticsResponse playerStatistics1);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProfileDataServiceChannel : StrategoApp.ProfileService.IProfileDataService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProfileDataServiceClient : System.ServiceModel.DuplexClientBase<StrategoApp.ProfileService.IProfileDataService>, StrategoApp.ProfileService.IProfileDataService {
        
        public ProfileDataServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public ProfileDataServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public ProfileDataServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ProfileDataServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ProfileDataServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void GetPlayerStatistics(int playerId) {
            base.Channel.GetPlayerStatistics(playerId);
        }
        
        public System.Threading.Tasks.Task GetPlayerStatisticsAsync(int playerId) {
            return base.Channel.GetPlayerStatisticsAsync(playerId);
        }
        
        public void LogOut(int playerId) {
            base.Channel.LogOut(playerId);
        }
        
        public System.Threading.Tasks.Task LogOutAsync(int playerId) {
            return base.Channel.LogOutAsync(playerId);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProfileService.IProfileModifierService", CallbackContract=typeof(StrategoApp.ProfileService.IProfileModifierServiceCallback))]
    public interface IProfileModifierService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfileModifierService/UpdatePlayerProfile", ReplyAction="http://tempuri.org/IProfileModifierService/UpdatePlayerProfileResponse")]
        void UpdatePlayerProfile(StrategoApp.ProfileService.PlayerInfoShownDTO newProfile);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfileModifierService/UpdatePlayerProfile", ReplyAction="http://tempuri.org/IProfileModifierService/UpdatePlayerProfileResponse")]
        System.Threading.Tasks.Task UpdatePlayerProfileAsync(StrategoApp.ProfileService.PlayerInfoShownDTO newProfile);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProfileModifierServiceCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IProfileModifierService/ReceiveUpdatePlayerProfile")]
        void ReceiveUpdatePlayerProfile(StrategoApp.ProfileService.PlayerInfoResponse result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProfileModifierServiceChannel : StrategoApp.ProfileService.IProfileModifierService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProfileModifierServiceClient : System.ServiceModel.DuplexClientBase<StrategoApp.ProfileService.IProfileModifierService>, StrategoApp.ProfileService.IProfileModifierService {
        
        public ProfileModifierServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public ProfileModifierServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public ProfileModifierServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ProfileModifierServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ProfileModifierServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void UpdatePlayerProfile(StrategoApp.ProfileService.PlayerInfoShownDTO newProfile) {
            base.Channel.UpdatePlayerProfile(newProfile);
        }
        
        public System.Threading.Tasks.Task UpdatePlayerProfileAsync(StrategoApp.ProfileService.PlayerInfoShownDTO newProfile) {
            return base.Channel.UpdatePlayerProfileAsync(newProfile);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProfileService.IPlayerFriendsListService", CallbackContract=typeof(StrategoApp.ProfileService.IPlayerFriendsListServiceCallback))]
    public interface IPlayerFriendsListService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayerFriendsListService/GetPlayerFriendsList", ReplyAction="http://tempuri.org/IPlayerFriendsListService/GetPlayerFriendsListResponse")]
        void GetPlayerFriendsList(int playerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayerFriendsListService/GetPlayerFriendsList", ReplyAction="http://tempuri.org/IPlayerFriendsListService/GetPlayerFriendsListResponse")]
        System.Threading.Tasks.Task GetPlayerFriendsListAsync(int playerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayerFriendsListService/GetConnectedFriends", ReplyAction="http://tempuri.org/IPlayerFriendsListService/GetConnectedFriendsResponse")]
        void GetConnectedFriends(int playerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayerFriendsListService/GetConnectedFriends", ReplyAction="http://tempuri.org/IPlayerFriendsListService/GetConnectedFriendsResponse")]
        System.Threading.Tasks.Task GetConnectedFriendsAsync(int playerId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPlayerFriendsListServiceCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IPlayerFriendsListService/PlayerFriendsList")]
        void PlayerFriendsList(StrategoApp.ProfileService.PlayerFriendsResponse playerFriends);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPlayerFriendsListServiceChannel : StrategoApp.ProfileService.IPlayerFriendsListService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PlayerFriendsListServiceClient : System.ServiceModel.DuplexClientBase<StrategoApp.ProfileService.IPlayerFriendsListService>, StrategoApp.ProfileService.IPlayerFriendsListService {
        
        public PlayerFriendsListServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public PlayerFriendsListServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public PlayerFriendsListServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public PlayerFriendsListServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public PlayerFriendsListServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void GetPlayerFriendsList(int playerId) {
            base.Channel.GetPlayerFriendsList(playerId);
        }
        
        public System.Threading.Tasks.Task GetPlayerFriendsListAsync(int playerId) {
            return base.Channel.GetPlayerFriendsListAsync(playerId);
        }
        
        public void GetConnectedFriends(int playerId) {
            base.Channel.GetConnectedFriends(playerId);
        }
        
        public System.Threading.Tasks.Task GetConnectedFriendsAsync(int playerId) {
            return base.Channel.GetConnectedFriendsAsync(playerId);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProfileService.IOtherProfileDataService", CallbackContract=typeof(StrategoApp.ProfileService.IOtherProfileDataServiceCallback))]
    public interface IOtherProfileDataService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOtherProfileDataService/GetOtherPlayerInfo", ReplyAction="http://tempuri.org/IOtherProfileDataService/GetOtherPlayerInfoResponse")]
        void GetOtherPlayerInfo(int playerId, int requesterPlayerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOtherProfileDataService/GetOtherPlayerInfo", ReplyAction="http://tempuri.org/IOtherProfileDataService/GetOtherPlayerInfoResponse")]
        System.Threading.Tasks.Task GetOtherPlayerInfoAsync(int playerId, int requesterPlayerId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IOtherProfileDataServiceCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IOtherProfileDataService/ReceiveOtherPlayerInfo")]
        void ReceiveOtherPlayerInfo(StrategoApp.ProfileService.OtherPlayerInfoResponse response);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IOtherProfileDataServiceChannel : StrategoApp.ProfileService.IOtherProfileDataService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OtherProfileDataServiceClient : System.ServiceModel.DuplexClientBase<StrategoApp.ProfileService.IOtherProfileDataService>, StrategoApp.ProfileService.IOtherProfileDataService {
        
        public OtherProfileDataServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public OtherProfileDataServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public OtherProfileDataServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public OtherProfileDataServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public OtherProfileDataServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void GetOtherPlayerInfo(int playerId, int requesterPlayerId) {
            base.Channel.GetOtherPlayerInfo(playerId, requesterPlayerId);
        }
        
        public System.Threading.Tasks.Task GetOtherPlayerInfoAsync(int playerId, int requesterPlayerId) {
            return base.Channel.GetOtherPlayerInfoAsync(playerId, requesterPlayerId);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProfileService.ITopPlayersListService", CallbackContract=typeof(StrategoApp.ProfileService.ITopPlayersListServiceCallback))]
    public interface ITopPlayersListService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITopPlayersListService/GetTopPlayersList", ReplyAction="http://tempuri.org/ITopPlayersListService/GetTopPlayersListResponse")]
        void GetTopPlayersList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITopPlayersListService/GetTopPlayersList", ReplyAction="http://tempuri.org/ITopPlayersListService/GetTopPlayersListResponse")]
        System.Threading.Tasks.Task GetTopPlayersListAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITopPlayersListServiceCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITopPlayersListService/TopPlayersList")]
        void TopPlayersList([System.ServiceModel.MessageParameterAttribute(Name="topPlayersList")] StrategoApp.ProfileService.TopPlayersResponse topPlayersList1);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITopPlayersListServiceChannel : StrategoApp.ProfileService.ITopPlayersListService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TopPlayersListServiceClient : System.ServiceModel.DuplexClientBase<StrategoApp.ProfileService.ITopPlayersListService>, StrategoApp.ProfileService.ITopPlayersListService {
        
        public TopPlayersListServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public TopPlayersListServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public TopPlayersListServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public TopPlayersListServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public TopPlayersListServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void GetTopPlayersList() {
            base.Channel.GetTopPlayersList();
        }
        
        public System.Threading.Tasks.Task GetTopPlayersListAsync() {
            return base.Channel.GetTopPlayersListAsync();
        }
    }
}
